export const NATS_SERVICES = 'NATS_SERVICES';
export const REDIS_PUB_CLIENT = 'REDIS_PUB_CLIENT';
export const REDIS_SUB_CLIENT = 'REDIS_SUB_CLIENT';
export const TICKET_CALLED_EVENT = 'TICKET_CALLED_EVENT';
export const QUEUE_UPDATE_EVENT = 'QUEUE_UPDATE_EVENT';
export const TICKET_COMPLETED_EVENT = 'TICKET_COMPLETED_EVENT';
